version: '3'

dotenv: [env/.dev.env]

tasks:
  docker:postgres:start:
    desc: Start a Postgres server via docker compose
    cmds:
      - docker compose up -d db

  docker:postgres:stop:
    desc: Stops Postgres server via docker compose
    cmds:
      - docker compose stop db

  docker:server:start:
    desc: Start the Greenlight API server via docker compose
    cmds:
      - docker compose up -d --build api

  docker:server:stop:
    desc: Stop the Greenlight API server via docker compose
    cmds:
      - docker compose stop api

  db:setup:
    desc: Setup the database and the database user used by the greenlight app
    cmds:
      - go run ./cmd/db setup

  db:teardown:
    desc: Teardown the database and the database user used by the greenlight app
    cmds:
      - go run ./cmd/db teardown

  db:migrations:new:
    desc: Creates a new migration file
    cmds:
      - echo "Creating migration files for {{.CLI_ARGS}}..."
      - migrate create -seq -ext=.sql -dir=./migrations {{.CLI_ARGS}}

  db:migrations:up:
    desc: Runs up migrations
    cmds:
     - echo "Running up migrations..."
     - migrate -path ./migrations -database ${GREENLIGHT_DB_DSN} up

  db:migrations:down:
    desc: Runs down migrations
    cmds:
      - echo "Running down migrations..."
      - migrate -path ./migrations -database ${GREENLIGHT_DB_DSN} down

  server:start:
    desc: Start the Greenlight API server
    cmds:
      - go run ./cmd/api {{.CLI_ARGS}}

  smoketest:
    desc: Run the smoke test
    dotenv: [env/.smoketest.env]
    cmds:
      - defer: go run ./cmd/db teardown
      - go run ./cmd/db setup
      - migrate -path ./migrations -database $GREENLIGHT_DB_DSN up
      - ./smoke_test.sh

  audit:
    desc: Run quality control audits
    cmds:
      - echo "Tidying and verifying module dependencies..."
      - go mod tidy
      - go mod verify
      - echo "Formatting code..."
      - go fmt ./...
      - echo "Vetting code..."
      - go vet ./...
      - staticcheck ./...
      - echo "Checking vulnerabilities..."
      - govulncheck ./...

  test:
    desc: Run all tests
    cmds:
      - go test -json -v --coverprofile=coverage.out ./... 2>&1 | gotestfmt -hide "successful-tests, empty-packages"
